---
ID: "235d2d0b-9a18-42ec-b8b9-77c82590dabc"
Parent: "bad20a3e-c6fb-4211-be75-571cbfde0110"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Storefront/Data Templates/Commerce Server Configuration/Storefront Configuration
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150308T092732Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
