---
ID: "533488ef-6789-4942-b360-3260bdb22624"
Parent: "5107a7da-8ce3-40f9-81ea-30a48ec6ae35"
Template: "bfafe295-9df8-4a3e-9ca1-7d161da74538"
Path: /sitecore/client/Commerce/Default Commerce Data Service Settings
DB: core
SharedFields:
- ID: "6f1ec156-0abc-4aab-9184-42e90eed5904"
  Hint: ShopName
  Value: Storefront
- ID: "93d751cc-3739-457b-b44d-2aed8b8da038"
  Hint: DataServiceUrl
  Value: "http://habitat.commerceengine.dev.local:5000/api/"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160518T162950Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
