---
ID: "97073912-c895-4fc7-a283-dd8dd309ccd7"
Parent: "50ca28d4-c93c-435b-92da-866276a1bfdf"
Template: "f73f2dd4-f64f-4134-90b2-0b16e37df630"
Path: /sitecore/content/Storefront/Global/Site Spots/Product List Header
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141104T030331
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
