---
ID: "83da4c94-d96c-4957-b026-6c9ac77db964"
Parent: "06c80404-7020-45f1-b818-cb650f71dc69"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Storefront/Catalog/ProductInformation
DB: master
SharedFields:
- ID: "11490da4-bbc2-4397-8df2-6db2ef445081"
  Hint: VaryByUrlPath
  Type: Checkbox
  Value: 1
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Storefront/Rendering Datasources/Product Information
- ID: "3d08db46-2267-41b0-bc52-be69fd618633"
  Hint: Cacheable
  Type: Checkbox
  Value: 1
- ID: "8d9232b0-613f-440b-a2fa-dcdd80fbd33e"
  Hint: VaryByLogin
  Type: Checkbox
  Value: 1
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: 
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{EA8AB448-6F4A-4B29-A652-C7A9F078836F}" />
- ID: "c81ed375-7c73-4815-8ea5-8ccfc4056929"
  Hint: VaryByCurrency
  Type: Checkbox
  Value: 1
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: ProductInformation
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Catalog
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141023T062510
