---
ID: "431ccb66-ad67-472f-b11a-5908c822b768"
Parent: "770ef91b-36cc-42bf-865e-b76633fac34b"
Template: "867dacb1-9a99-4151-beaa-e39f5048f5a4"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161127T132241Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
