---
ID: "3b3e5ebd-9c00-4464-a7b1-cb2c6af7f850"
Parent: "f73f2dd4-f64f-4134-90b2-0b16e37df630"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Storefront/Rendering Datasources/Product List Header/Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: wordprocessing/32x32/header.png
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141105T070018
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
