---
ID: "fe29abe9-7f30-4841-82bf-9c6f3c1ef249"
Parent: "e0789c72-a245-41ec-aae3-adaa1190ad76"
Template: "54e7880d-2621-49ea-a417-982fcd372903"
Path: /sitecore/content/Storefront/Retail Campaigns/Message Types/OneTime/Default
DB: master
SharedFields:
- ID: "19b597d3-2edd-4ae2-aefe-4a94c7f10e31"
  Hint: __Source Item
  Value: "sitecore://master/{D69DC4EC-905D-4EE0-8CE6-A1E1A44E7D85}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{D69DC4EC-905D-4EE0-8CE6-A1E1A44E7D85}?lang=en&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170322T160613Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
