---
ID: "abefd239-f760-4249-a568-fd903ad9a4cf"
Parent: "51541163-54af-4d41-b86e-0b2e3a26b215"
Template: "81afaa32-f1b0-47de-a8e6-3e443a06510e"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/Storefront/Currency Configuration
DB: master
SharedFields:
- ID: "f8abfa72-0fba-44a5-9122-cf11acb0ea61"
  Hint: Currency Set
  Value: "{4B494292-598E-4A61-A156-D7501F7953ED}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161207T070315Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
