---
ID: "8767aff3-f7f2-47ec-92c0-8a24b0f18967"
Parent: "8817567e-830e-4b71-b072-fe7681ec832f"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Feature/Commerce/Catalog/Product List Header
DB: master
SharedFields:
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: 
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: 
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: 
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: ProductListHeader
- ID: "e514a1eb-ddba-44f7-8528-82ca2280f778"
  Hint: JavaScript assets
  Value: |
    /Scripts/Catalog/jsuri.js
    /Scripts/Catalog/product-list.js
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Catalog
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141023T062602
