---
ID: "0f71a71c-55c7-498f-bfc7-30c8315db6fb"
Parent: "37974069-d340-47b9-956f-49afc39b5169"
Template: "37974069-d340-47b9-956f-49afc39b5169"
Path: /sitecore/templates/Storefront/Rendering Datasources/SearchBar/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150922T124723Z
    - ID: "ee8cd542-f88e-49c7-8bb4-9190edad1272"
      Hint: Search
      Value: Search
