---
ID: "c0b824fa-77b3-4a66-b8ba-0b436fc6c7d9"
Parent: "2479dc14-604a-4fd3-a2ca-10e6954a95cc"
Template: "c7d9d293-4ef8-4380-8e10-c4632e729f39"
Path: /sitecore/content/Storefront/Home/_Local/Product 1
DB: master
SharedFields:
- ID: "e8ab122c-6f54-4d4e-aec6-f81addc558fc"
  Hint: TeaserLink
  Value: |
    <link text="View" linktype="external" url="/shop/Cameras_cameras/Optix180MPDSLRCamerawith18-55mmLens_7042074" anchor="" target="" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0f6b5546-e0ab-4487-81de-640c1aa1b65b"
      Hint: TeaserImage
      Value: |
        <image mediaid="{A1D2E82E-35F6-42C9-A572-3C9E62462C1C}" />
    - ID: "13d97a52-7c4e-407c-960d-fadde8a3c1b1"
      Hint: TeaserSummary
      Value: "Utilizing an 18.2-megapixel sensor, this Optix digital camera allows you to take sharp photographs and true HD video. Built-in Wi-Fi helps simplify file sharing across devices."
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170105T120133Z
    - ID: "3f7e7e3a-4e8e-4639-b079-fc5aeff172f5"
      Hint: Teaser Label
      Value: Cameras
    - ID: "4a59d072-5b41-4a79-a157-2b2ccac10f2b"
      Hint: TeaserTitle
      Value: "Optix 18.0MP DSLR Camera with 18-55mm Lens"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
