---
ID: "74b6897e-2e5e-41da-ad73-f232e8b0b5aa"
Parent: "1a61b0cc-d770-4086-adfe-4a698a353d90"
Template: "1a61b0cc-d770-4086-adfe-4a698a353d90"
Path: /sitecore/templates/Project/Retail/Content Types/Folders/Landing Pages Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {49C651BA-4004-40A9-9B0F-E95D0573F3AE}
    {B2BE0A70-179C-4BB2-86EB-D7C6189F5584}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170301T225413Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
