---
ID: "ce793b56-a7b3-4a19-b18c-d1271a40499c"
Parent: "2479dc14-604a-4fd3-a2ca-10e6954a95cc"
Template: "c7d9d293-4ef8-4380-8e10-c4632e729f39"
Path: /sitecore/content/Storefront/Home/_Local/Product 2
DB: master
SharedFields:
- ID: "e8ab122c-6f54-4d4e-aec6-f81addc558fc"
  Hint: TeaserLink
  Value: |
    <link text="View" linktype="external" url="/shop/Televisions_televisions/HelixSpectra75â4KLEDUltraHDTelevision_6042265" anchor="" target="" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "0f6b5546-e0ab-4487-81de-640c1aa1b65b"
      Hint: TeaserImage
      Value: |
        <image mediaid="{3B286DFB-34D6-48F8-9748-AA179720A9D4}" />
    - ID: "13d97a52-7c4e-407c-960d-fadde8a3c1b1"
      Hint: TeaserSummary
      Value: "Enjoy incredible picture and dramatic detail with 4X the resolution of full HD. Enjoy incredible hues of color with technology that blends digital color for near-perfect representation."
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170105T121021Z
    - ID: "3f7e7e3a-4e8e-4639-b079-fc5aeff172f5"
      Hint: Teaser Label
      Value: Televisions
    - ID: "4a59d072-5b41-4a79-a157-2b2ccac10f2b"
      Hint: TeaserTitle
      Value: Spectra 75” 4K LED Ultra HD Television
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
