---
ID: "62fc74d5-ab1e-4462-8b4b-3c2469111302"
Parent: "64bd9b66-1baa-4955-bb06-3abb9b3fb207"
Template: "c82dc5ff-09ef-4403-96d3-3caf377b8c5b"
Path: /sitecore/content/Storefront/Settings/Datasources/productsearch
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170315T044905Z
    - ID: "498dd5b6-7dae-44a7-9213-1d32596ad14f"
      Hint: DatasourceTemplate
      Value: /sitecore/templates/Storefront/Rendering Datasources/Product Search Lists
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "5fe1cc43-f86c-459c-a379-cd75950d85af"
      Hint: DatasourceLocation
      Value: /sitecore/content/Storefront/Global/Product Search Lists
