---
ID: "95126a79-7bc5-4321-8b6f-cde2a409db4e"
Parent: "64bd9b66-1baa-4955-bb06-3abb9b3fb207"
Template: "c82dc5ff-09ef-4403-96d3-3caf377b8c5b"
Path: /sitecore/content/Storefront/Settings/Datasources/productcategory
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170315T045250Z
    - ID: "498dd5b6-7dae-44a7-9213-1d32596ad14f"
      Hint: DatasourceTemplate
      Value: /sitecore/templates/Commerce/Catalog/Commerce Category
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "5fe1cc43-f86c-459c-a379-cd75950d85af"
      Hint: DatasourceLocation
      Value: /sitecore/content/Storefront/Home/Product catalog
