---
ID: "45d10b64-c264-4230-b17f-f81d790fa15a"
Parent: "23dd8a7e-1710-446b-b712-c223716505e9"
Template: "23dd8a7e-1710-446b-b712-c223716505e9"
Path: /sitecore/templates/Storefront/Page Templates/GiftCard Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r>
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{83EEB1E8-D75E-4ABE-984A-A1275E5C27F7}">
        <r
          id="{E7AE3F87-CF66-40F2-A9F5-33ECF08BC777}"
          ph="head"
          uid="{D17C7928-A5AE-4E11-8A08-7E7C77D59415}" />
        <r
          id="{3389CAFC-000C-41E5-921C-92821B3DB7B5}"
          ph="head"
          uid="{56E5999F-6370-4AA7-BDD5-2C486F35963D}" />
        <r
          id="{C28B9C5F-8E01-42EC-ADF6-3324FAF92C7D}"
          ph="header-top"
          uid="{C9E1D6CC-6AF4-4C10-A434-87DC004511E1}" />
        <r
          ds="{C5BCE776-8E95-44F9-AB65-52631BE0DB3C}"
          id="{69B9C355-004B-4268-BB1E-2F725B8752B7}"
          ph="right-header-top"
          uid="{4DD26A39-B79A-4C35-A9B5-C3BB71635265}" />
        <r
          id="{E26A158B-FA1E-4E9B-8622-E4458243FF46}"
          ph="navbar"
          uid="{412E4739-4A73-4C20-962C-FED66C9E2140}" />
        <r
          id="{A47C8288-7D4C-45FF-B75F-4AEDBF58A02D}"
          ph="navbar-left"
          uid="{46C70088-BCB4-4158-977B-2D14E380143D}" />
        <r
          ds="{889A6934-BCDC-4294-94B7-6D141E7312B4}"
          id="{CFD437A6-404A-4C8C-8A41-EED2FB86D5DE}"
          ph="navbar-center"
          uid="{3B4B2D49-3C4D-4002-B58B-F2B0573BA1AA}" />
        <r
          id="{8832BA30-99C3-4D20-9B1C-237D910A153F}"
          ph="navbar-right"
          uid="{2CF96924-BC5A-4117-987C-0E2735D472A0}" />
        <r
          ds="{B5F108D3-651F-4344-BF9B-8F10675DDBA0}"
          id="{FAA386D8-192F-4762-839D-D637BD11549F}"
          ph="navbar-activity"
          uid="{6CA1D0B5-8F67-4E61-926B-D04EC21CFB88}" />
        <r
          id="{B6C0593E-1C35-4C61-8DB5-E7C7AA19D955}"
          ph="navbar-activity"
          uid="{AF81EE23-02E6-4073-9232-AEBD79425630}" />
        <r
          ds="{9988B682-59C7-4319-8BF9-7071F132A5AD}"
          id="{9AA8E388-A6BD-46E1-A73B-DDEF601DE6F8}"
          ph="navbar-activity"
          uid="{15EB1F17-5175-4EC5-902D-E142D1196AE2}" />
        <r
          id="{A2216CA7-B205-4042-A345-72117D0086C3}"
          par="UseStaticPlaceholderNames=1"
          ph="page-layout"
          uid="{9F3A9F8F-0175-46F2-9C7D-0ADA1B7B38DC}" />
        <r
          id="{11680CDD-D6CF-4F1A-A770-B9815A6F7CEC}"
          ph="/page-layout/page-header"
          uid="{C6F73193-0562-47A7-A004-148AD383EB36}" />
        <r
          id="{D201A487-5099-48A1-8189-55944F70C6CB}"
          par="UseStaticPlaceholderNames=1"
          ph="page-layout"
          uid="{6D5CD8E2-86F0-4406-9F97-08D1A43BEEF1}" />
        <r
          id="{0AD8EC59-33EC-4103-AAD4-F3A49BFDB92C}"
          par="UseStaticPlaceholderNames=1"
          ph="/page-layout/section"
          uid="{B049AE63-7778-41F2-AA33-1AB3C3BE542B}" />
        <r
          id="{E45FD475-ADD0-42A0-A297-ADFE98B47A4A}"
          ph="/page-layout/section/col-huge"
          uid="{3858834C-1AF1-40F3-80AE-E0B818EA5C4C}" />
        <r
          id="{A7CEEE33-046A-49DA-8D0B-636BAC05F97F}"
          ph="productimages"
          uid="{CBF8B050-CFD6-4013-83BF-5EF3AAF64682}" />
        <r
          id="{49424190-0EFA-4414-8D18-4569CC8EA5FD}"
          ph="productrating"
          uid="{3B217F90-4061-48A6-BDCF-23A624D69491}" />
        <r
          id="{AAF9B3B2-BE53-4B85-BDBF-E7704C0B28D2}"
          ph="socialconnector"
          uid="{8C2C1F8D-59F1-4B59-8B17-FC5BE9CF1765}" />
        <r
          ds="{2CD89BFE-2CCB-420F-8913-68A063BA4AE8}"
          id="{700D7CE2-8F0B-410A-AA29-1683BA6FFC9C}"
          ph="productinformation"
          uid="{1246D83F-4D53-4A33-A619-D3E0FF4F550B}" />
        <r
          ds="{BF9E2E06-E978-413F-BA77-FF8AFF537B68}"
          id="{619FBEF7-DBC4-4F09-9922-F0701BC887E6}"
          ph="addtocart"
          uid="{AB30B911-D624-44FD-9367-09094970F6A5}" />
        <r
          ds="{E48E2CCA-493D-410D-9B15-B2E1A0939730}"
          id="{04ADF67D-1449-4DAC-A496-CA3B504AAF71}"
          ph="shareandprint"
          uid="{93A1C3F2-8B63-43AF-AF7B-7CE6F269E9FB}" />
        <r
          id="{7B9B4279-22EC-4274-901F-96B1A5CAB999}"
          ph="checkgiftcardbalance"
          uid="{890EB9AE-89DE-490F-8758-CACF59DFB432}" />
        <r
          id="{299FD8EA-2CFD-4A69-9CA4-7EA24CD34A46}"
          ph="footer"
          uid="{F2636EC5-4EF6-4E4E-8982-4D669D1CE6F8}" />
        <r
          id="{DE648E12-A568-4919-802E-A688EBC9B9F3}"
          par="UseStaticPlaceholderNames=1"
          ph="/footer/section"
          uid="{DDAF879C-4CC2-4615-A5A2-86AA848D006C}" />
        <r
          ds="{C5BCE776-8E95-44F9-AB65-52631BE0DB3C}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-1"
          uid="{DB7FE336-69F0-48C5-92A0-BDE869EBED4E}" />
        <r
          ds="{C5BCE776-8E95-44F9-AB65-52631BE0DB3C}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-2"
          uid="{B03DC6D0-A584-4EB4-9AF0-74A6A9C29545}" />
        <r
          ds="{C5BCE776-8E95-44F9-AB65-52631BE0DB3C}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-3"
          uid="{C0E759B7-042F-4BEE-B157-3217CA4BEC20}" />
        <r
          ds="{C5BCE776-8E95-44F9-AB65-52631BE0DB3C}"
          id="{F366FBA9-EF26-4007-988A-63CB64649C46}"
          ph="/footer/section/col-narrow-4"
          uid="{70CF4831-AA88-4419-A7C2-BE1349651B1F}" />
        <r
          id="{7DAE9F23-890F-4E06-99A7-CCEDB74D3D8E}"
          ph="postfooter"
          uid="{814B2AF7-C8B1-4F73-8EBC-CC9B897A697A}" />
        <r
          id="{CED18F24-62C2-445E-B0D9-045E3325297B}"
          ph="page-sidebar"
          uid="{1FB26D6A-B9F9-489C-8FA2-DCD9CADA8F2A}" />
      </d>
      <d
        id="{46D2F427-4CE5-4E1F-BA10-EF3636F43534}"
        l="{158292D8-6523-4052-8DEF-60DD6F112A09}">
        <r
          id="{A093583B-6870-44AD-B14E-54703B32E9B9}"
          ph="middle"
          uid="{72BA2DFF-7EC5-432A-9BBA-1A6641D1A4D1}" />
        <r
          id="{E45FD475-ADD0-42A0-A297-ADFE98B47A4A}"
          ph="center"
          uid="{8473084D-CC59-4227-80A0-737703ECC6FF}" />
        <r
          id="{A7CEEE33-046A-49DA-8D0B-636BAC05F97F}"
          ph="productimages"
          uid="{C7CB26D2-6EAE-459E-971F-F7054794E07C}" />
        <r
          id="{49424190-0EFA-4414-8D18-4569CC8EA5FD}"
          ph="productrating"
          uid="{537F7E73-77EA-4C1B-872E-831A840E1415}" />
        <r
          ds="{2CD89BFE-2CCB-420F-8913-68A063BA4AE8}"
          id="{700D7CE2-8F0B-410A-AA29-1683BA6FFC9C}"
          ph="productinformation"
          uid="{24B947CE-E076-49AE-B51B-83F02CA1E36D}" />
      </d>
    </r>
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{9B706406-941F-4707-BBB1-A298CC0FEE82}">
              <p:d />
            </r>
            <r
              uid="{93A1C3F2-8B63-43AF-AF7B-7CE6F269E9FB}"
              p:before="r[@uid='{890EB9AE-89DE-490F-8758-CACF59DFB432}']"
              s:ds="{E48E2CCA-493D-410D-9B15-B2E1A0939730}"
              s:id="{04ADF67D-1449-4DAC-A496-CA3B504AAF71}"
              s:par=""
              s:ph="shareandprint" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141022T082640
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{9B706406-941F-4707-BBB1-A298CC0FEE82}">
              <p:d />
            </r>
            <r
              uid="{93A1C3F2-8B63-43AF-AF7B-7CE6F269E9FB}"
              p:before="r[@uid='{890EB9AE-89DE-490F-8758-CACF59DFB432}']"
              s:ds="{E48E2CCA-493D-410D-9B15-B2E1A0939730}"
              s:id="{04ADF67D-1449-4DAC-A496-CA3B504AAF71}"
              s:par=""
              s:ph="shareandprint" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141022T082640
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{9B706406-941F-4707-BBB1-A298CC0FEE82}">
              <p:d />
            </r>
            <r
              uid="{93A1C3F2-8B63-43AF-AF7B-7CE6F269E9FB}"
              p:before="r[@uid='{890EB9AE-89DE-490F-8758-CACF59DFB432}']"
              s:ds="{E48E2CCA-493D-410D-9B15-B2E1A0939730}"
              s:id="{04ADF67D-1449-4DAC-A496-CA3B504AAF71}"
              s:par=""
              s:ph="shareandprint" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141022T082640
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{9B706406-941F-4707-BBB1-A298CC0FEE82}">
              <p:d />
            </r>
            <r
              uid="{93A1C3F2-8B63-43AF-AF7B-7CE6F269E9FB}"
              p:before="r[@uid='{890EB9AE-89DE-490F-8758-CACF59DFB432}']"
              s:ds="{E48E2CCA-493D-410D-9B15-B2E1A0939730}"
              s:id="{04ADF67D-1449-4DAC-A496-CA3B504AAF71}"
              s:par=""
              s:ph="shareandprint" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141022T082640
