---
ID: "d97dc323-9a54-47c4-98f0-97fd2301d24e"
Parent: "d782ac04-9757-448f-961b-fc956fa37bf2"
Template: "d782ac04-9757-448f-961b-fc956fa37bf2"
Path: /sitecore/templates/Storefront/Page Templates/UserPendingActivation Page/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160407T201937Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
