---
ID: "3eb9c5df-f1e7-44bc-9ec0-1729662b6a2f"
Parent: "20a60b05-6330-49f2-9ffc-821b8085b319"
Template: "9795c562-98d9-4a9e-bc9c-c6b7a079fdf4"
Path: /sitecore/content/Storefront/Retail Campaigns/Message Types/Triggered/Default
DB: master
SharedFields:
- ID: "19b597d3-2edd-4ae2-aefe-4a94c7f10e31"
  Hint: __Source Item
  Value: "sitecore://master/{3913FBBA-2293-4C8F-8542-B949A6A007BB}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "ba69b6e7-fa6b-4963-af17-77cb45797628"
  Hint: Campaigns Position
  Value: "{B3807B08-E8CD-4109-BFBD-FBBA4813B297}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{3913FBBA-2293-4C8F-8542-B949A6A007BB}?lang=en&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170322T160614Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
