---
ID: "e78c5f21-a063-48dd-ba17-c8967065769d"
Parent: "51541163-54af-4d41-b86e-0b2e3a26b215"
Template: "762364a6-3ccb-43d2-9acb-c889db0f7fcf"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/Storefront/Country Region configuration
DB: master
SharedFields:
- ID: "6d8c6738-20ec-4ca0-b9ee-dc6b64ca224f"
  Hint: "Countries-Regions"
  Type: Multilist
  Value: |
    {9E9E8CB4-B03D-4650-9388-2F73CD0AD28F}
    {60D23160-C39D-4B72-89DB-489CCB57276A}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170314T001321Z
