@echo off
setlocal

SET ROOT_PATH=%1
SET DESTINATION_PATH=%2

IF NOT DEFINED ROOT_PATH SET ROOT_PATH=%~dp0
IF NOT DEFINED DESTINATION_PATH SET DESTINATION_PATH=C:\inetpub\CFRefStorefront\Website

CLS

ECHO "Root Path is %ROOT_PATH%"

PUSHD %ROOT_PATH%

@REM Copy Views...

XCOPY /S /I /R /Y "..\..\Common\CommonSettings\Views" "%DESTINATION_PATH%\Views\"
XCOPY /S /I /R /Y "..\CSF\Views" "%DESTINATION_PATH%\Views\"

POPD