---
ID: "8e497ed0-714d-445f-b861-835241dbe42a"
Parent: "ca2e00b1-0917-44a5-ad05-5fc3167aaa0c"
Template: "4ec92bc2-1ea9-4b44-ae01-69243c463977"
Path: /sitecore/Commerce/Storefront Configuration
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151001T103553Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
