---
ID: "2c30b030-2707-4dca-b15f-abee932590d5"
Parent: "bc5f0baa-ebd6-49b4-9800-70c540b57760"
Template: "bc5f0baa-ebd6-49b4-9800-70c540b57760"
Path: /sitecore/templates/Storefront/Base Templates/Storefront UI Element/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150915T082114Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
