---
ID: "feecd9c0-b050-4c7e-abc3-a07e1002f330"
Parent: "ce35efe0-01ea-4f43-b124-66fc4b0663ef"
Template: "ce35efe0-01ea-4f43-b124-66fc4b0663ef"
Path: /sitecore/templates/Storefront/Folder Templates/Pages Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {CE35EFE0-01EA-4F43-B124-66FC4B0663EF}
    {16E859D2-6542-407A-AC65-F34BCAD3EB3D}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141117T065337
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
