---
ID: "c81832cd-381f-49a5-a6d7-94d949191316"
Parent: "6aa57d38-7496-40fa-8c89-faaf91965a0c"
Template: "6aa57d38-7496-40fa-8c89-faaf91965a0c"
Path: /sitecore/templates/Storefront/Rendering Datasources/ErrorImage/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150113T182438Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "5e429fb1-f2d6-4f2d-996d-01a643786959"
      Hint: Image
      Value: |
        <image mediaid="{806CA914-607D-4481-8877-5D55C0F5F834}" alt="404" height="" width="" hspace="" vspace="" />
    - ID: "9830d923-dd76-4e52-a70f-3e6c6d373622"
      Hint: Link
      Value: |
        <link linktype="external" url="/" anchor="" target="" />
