---
ID: "7ac42470-b5fa-4d49-a63a-ef6f21154de2"
Parent: "87f2f2b9-cd50-4b78-9a27-fd853d5476b9"
Template: "87f2f2b9-cd50-4b78-9a27-fd853d5476b9"
Path: /sitecore/templates/Storefront/Rendering Datasources/Footer Navigation/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20141105T092049
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
