---
ID: "d7aefb49-1bcc-4edb-8501-faa98ecf9d21"
Parent: "a2cbb507-0279-4ef5-92a1-fba6621e0bc4"
Template: "a2cbb507-0279-4ef5-92a1-fba6621e0bc4"
Path: /sitecore/templates/Storefront/Page Templates/ForgotPassword Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{F5034347-7E92-41D7-B8EB-F51D1F1BCF1C}">
        <r
          id="{15A09072-CE89-4126-A9E4-17753FC726FF}"
          ph="top"
          uid="{0E2D603A-CF36-4EE2-B598-D2E06AEBD5AE}" />
        <r
          id="{B6C0593E-1C35-4C61-8DB5-E7C7AA19D955}"
          ph="topleft"
          uid="{17F64DAC-2A2C-4F61-A993-F3BC59203AA0}" />
        <r
          ds="{B5F108D3-651F-4344-BF9B-8F10675DDBA0}"
          id="{FAA386D8-192F-4762-839D-D637BD11549F}"
          par=""
          ph="topright"
          uid="{1B0865BA-8725-40D7-B472-5466055F1834}" />
        <r
          ds="{9988B682-59C7-4319-8BF9-7071F132A5AD}"
          id="{9AA8E388-A6BD-46E1-A73B-DDEF601DE6F8}"
          par=""
          ph="topcenter"
          uid="{8C308774-5362-4996-A416-527ED85204F1}" />
        <r
          id="{11680CDD-D6CF-4F1A-A770-B9815A6F7CEC}"
          ph="messages"
          uid="{37F8060A-568D-4ADA-B607-B3306CBEAB33}" />
        <r
          id="{79167FB2-C7E0-4124-81C9-61AFBB279388}"
          ph="navigation"
          uid="{1A6AE860-A323-460D-B8D7-CEFA22469672}" />
        <r
          id="{0FA59DDC-5AEB-4ADB-B64B-D8D03B351680}"
          ph="navigationextra"
          uid="{D0FFD21B-BDDF-4C59-A150-C43C76CABF37}" />
        <r
          ds="{98CE979E-638E-4EE0-AD7F-05164173F1C1}"
          id="{DC1B9040-8694-456A-A5E6-81996BD1B2AA}"
          par=""
          ph="navigationextraleft"
          uid="{5D2C83EE-F8CA-41B9-BBF2-03CBC74D3F52}" />
        <r
          ds="{5886D851-1625-48AE-A787-84FC5B5EB271}"
          id="{582FEA78-404C-44D8-B6B4-356B080F5A7C}"
          par=""
          ph="navigationextraright"
          uid="{0D3D37F8-ED81-4F72-B7C2-8D5AF8EB0094}" />
        <r
          ds="{889A6934-BCDC-4294-94B7-6D141E7312B4}"
          id="{CFD437A6-404A-4C8C-8A41-EED2FB86D5DE}"
          par=""
          ph="navigationmain"
          uid="{3C2F52A6-A439-456D-A812-04A831DB8A0F}" />
        <r
          id="{A093583B-6870-44AD-B14E-54703B32E9B9}"
          ph="middle"
          uid="{F720367A-12C1-4818-887C-EB6B70A32640}" />
        <r
          id="{2685E523-5828-4F75-9B4E-476EFE1DC2DC}"
          ph="center"
          uid="{977A116E-E4E3-4322-8917-267068421DA1}" />
        <r
          ds=""
          id="{E7439728-329C-49A0-9F95-0799EC15E98F}"
          par=""
          ph="center"
          uid="{3A867BC7-C621-445D-9BAA-F403F5B94957}" />
        <r
          ds="{F6504124-F766-43D0-824B-EB339CAE8E5F}"
          id="{2658217E-196A-4041-8F81-B8AFA7E377EE}"
          par=""
          ph="bottom"
          uid="{7208E256-3895-45C7-8141-F4D4A14265F8}" />
      </d>
      <d
        id="{46D2F427-4CE5-4E1F-BA10-EF3636F43534}"
        l="{158292D8-6523-4052-8DEF-60DD6F112A09}">
        <r
          id="{A093583B-6870-44AD-B14E-54703B32E9B9}"
          ph="middle"
          uid="{04D12DA0-BC8C-4FB6-B8BB-BB1F962C40C1}" />
        <r
          id="{2685E523-5828-4F75-9B4E-476EFE1DC2DC}"
          ph="center"
          uid="{FB4CDC88-57A5-4018-8034-8A196E990D12}" />
        <r
          id="{E7439728-329C-49A0-9F95-0799EC15E98F}"
          ph="center"
          uid="{8D56C3F9-245E-4A2F-BF8F-F00C828A10B9}" />
      </d>
    </r>
- ID: "fc59d69e-66fb-42de-8621-54c1966a745a"
  Hint: Email Address Placeholder
  Value: Email Address
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: "de-DE"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{46D2F427-4CE5-4E1F-BA10-EF3636F43534}"
            s:l="{158292D8-6523-4052-8DEF-60DD6F112A09}">
            <r
              uid="{04D12DA0-BC8C-4FB6-B8BB-BB1F962C40C1}"
              s:id="{A093583B-6870-44AD-B14E-54703B32E9B9}"
              s:ph="middle" />
            <r
              uid="{FB4CDC88-57A5-4018-8034-8A196E990D12}"
              s:id="{2685E523-5828-4F75-9B4E-476EFE1DC2DC}"
              s:ph="center" />
            <r
              uid="{8D56C3F9-245E-4A2F-BF8F-F00C828A10B9}"
              s:id="{E7439728-329C-49A0-9F95-0799EC15E98F}"
              s:ph="center" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150110T090022Z
    - ID: "42abb57f-ec16-4278-a08e-aa13169abd8b"
      Hint: Submit
      Value: Submit
    - ID: "980bbf2b-c208-4a75-b9ca-e1c51b6c45d0"
      Hint: Submitting
      Value: Submitting...
    - ID: "a3995f9e-3242-4f02-84e7-be95bb0cfce1"
      Hint: Fill Form Message
      Value: Please fill out the form below to reset your password.
    - ID: "a48dcff4-5ad2-4d4e-8e61-4e4c538770e7"
      Hint: Email Missing Message
      Value: The email is required.
    - ID: "c75de0e7-17ff-4086-8552-9d68b7667809"
      Hint: Image
      Value: |
        <image mediaid="{784E8A3C-9C91-40B7-B1B3-7072B6439AB8}" />
    - ID: "cd8c9707-fe7a-4d3e-912c-95f9f2d0007d"
      Hint: Cancel
      Value: Cancel
    - ID: "ed62d6a1-7371-476a-93d9-c95080613d47"
      Hint: Email
      Value: Email Address
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{46D2F427-4CE5-4E1F-BA10-EF3636F43534}"
            s:l="{158292D8-6523-4052-8DEF-60DD6F112A09}">
            <r
              uid="{04D12DA0-BC8C-4FB6-B8BB-BB1F962C40C1}"
              s:id="{A093583B-6870-44AD-B14E-54703B32E9B9}"
              s:ph="middle" />
            <r
              uid="{FB4CDC88-57A5-4018-8034-8A196E990D12}"
              s:id="{2685E523-5828-4F75-9B4E-476EFE1DC2DC}"
              s:ph="center" />
            <r
              uid="{8D56C3F9-245E-4A2F-BF8F-F00C828A10B9}"
              s:id="{E7439728-329C-49A0-9F95-0799EC15E98F}"
              s:ph="center" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150110T090022Z
    - ID: "42abb57f-ec16-4278-a08e-aa13169abd8b"
      Hint: Submit
      Value: Submit
    - ID: "980bbf2b-c208-4a75-b9ca-e1c51b6c45d0"
      Hint: Submitting
      Value: Submitting...
    - ID: "a3995f9e-3242-4f02-84e7-be95bb0cfce1"
      Hint: Fill Form Message
      Value: Please fill out the form below to reset your password.
    - ID: "a48dcff4-5ad2-4d4e-8e61-4e4c538770e7"
      Hint: Email Missing Message
      Value: The email is required.
    - ID: "c75de0e7-17ff-4086-8552-9d68b7667809"
      Hint: Image
      Value: |
        <image mediaid="{784E8A3C-9C91-40B7-B1B3-7072B6439AB8}" />
    - ID: "cd8c9707-fe7a-4d3e-912c-95f9f2d0007d"
      Hint: Cancel
      Value: Cancel
    - ID: "ed62d6a1-7371-476a-93d9-c95080613d47"
      Hint: Email
      Value: Email Address
- Language: "fr-FR"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{46D2F427-4CE5-4E1F-BA10-EF3636F43534}"
            s:l="{158292D8-6523-4052-8DEF-60DD6F112A09}">
            <r
              uid="{04D12DA0-BC8C-4FB6-B8BB-BB1F962C40C1}"
              s:id="{A093583B-6870-44AD-B14E-54703B32E9B9}"
              s:ph="middle" />
            <r
              uid="{FB4CDC88-57A5-4018-8034-8A196E990D12}"
              s:id="{2685E523-5828-4F75-9B4E-476EFE1DC2DC}"
              s:ph="center" />
            <r
              uid="{8D56C3F9-245E-4A2F-BF8F-F00C828A10B9}"
              s:id="{E7439728-329C-49A0-9F95-0799EC15E98F}"
              s:ph="center" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150110T090022Z
    - ID: "42abb57f-ec16-4278-a08e-aa13169abd8b"
      Hint: Submit
      Value: Submit
    - ID: "980bbf2b-c208-4a75-b9ca-e1c51b6c45d0"
      Hint: Submitting
      Value: Submitting...
    - ID: "a3995f9e-3242-4f02-84e7-be95bb0cfce1"
      Hint: Fill Form Message
      Value: Please fill out the form below to reset your password.
    - ID: "a48dcff4-5ad2-4d4e-8e61-4e4c538770e7"
      Hint: Email Missing Message
      Value: The email is required.
    - ID: "c75de0e7-17ff-4086-8552-9d68b7667809"
      Hint: Image
      Value: |
        <image mediaid="{784E8A3C-9C91-40B7-B1B3-7072B6439AB8}" />
    - ID: "cd8c9707-fe7a-4d3e-912c-95f9f2d0007d"
      Hint: Cancel
      Value: Cancel
    - ID: "ed62d6a1-7371-476a-93d9-c95080613d47"
      Hint: Email
      Value: Email Address
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{46D2F427-4CE5-4E1F-BA10-EF3636F43534}"
            s:l="{158292D8-6523-4052-8DEF-60DD6F112A09}">
            <r
              uid="{04D12DA0-BC8C-4FB6-B8BB-BB1F962C40C1}"
              s:id="{A093583B-6870-44AD-B14E-54703B32E9B9}"
              s:ph="middle" />
            <r
              uid="{FB4CDC88-57A5-4018-8034-8A196E990D12}"
              s:id="{2685E523-5828-4F75-9B4E-476EFE1DC2DC}"
              s:ph="center" />
            <r
              uid="{8D56C3F9-245E-4A2F-BF8F-F00C828A10B9}"
              s:id="{E7439728-329C-49A0-9F95-0799EC15E98F}"
              s:ph="center" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150110T090022Z
    - ID: "42abb57f-ec16-4278-a08e-aa13169abd8b"
      Hint: Submit
      Value: Submit
    - ID: "980bbf2b-c208-4a75-b9ca-e1c51b6c45d0"
      Hint: Submitting
      Value: Submitting...
    - ID: "a3995f9e-3242-4f02-84e7-be95bb0cfce1"
      Hint: Fill Form Message
      Value: Please fill out the form below to reset your password.
    - ID: "a48dcff4-5ad2-4d4e-8e61-4e4c538770e7"
      Hint: Email Missing Message
      Value: The email is required.
    - ID: "c75de0e7-17ff-4086-8552-9d68b7667809"
      Hint: Image
      Value: |
        <image mediaid="{784E8A3C-9C91-40B7-B1B3-7072B6439AB8}" />
    - ID: "cd8c9707-fe7a-4d3e-912c-95f9f2d0007d"
      Hint: Cancel
      Value: Cancel
    - ID: "ed62d6a1-7371-476a-93d9-c95080613d47"
      Hint: Email
      Value: Email Address
